# Generated by Django 2.2.1 on 2019-07-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='c_name',
            new_name='name',
        ),
    ]
