# Generated by Django 2.2.1 on 2019-07-21 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_auto_20190721_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='department',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='per_group', to='company_app.Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='per_com', to='company_app.Group'),
        ),
    ]
