# Generated by Django 2.2.1 on 2019-07-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0003_auto_20190721_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company_app.Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='per_group', to='company_app.Group'),
        ),
    ]
