# Generated by Django 2.2.3 on 2019-08-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0004_auto_20190721_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='coming_time',
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='per_company', to='company_app.Company'),
        ),
    ]
