# Generated by Django 2.2.1 on 2019-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='put_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
