# Generated by Django 2.2.1 on 2019-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_put_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='put_time',
            field=models.DateTimeField(null=True),
        ),
    ]
