# Generated by Django 2.2.3 on 2019-10-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtSign',
            fields=[
                ('HtSign_num', models.AutoField(primary_key=True, serialize=False)),
                ('ht_num', models.CharField(max_length=11)),
                ('ybs_num', models.CharField(max_length=11)),
                ('tb_num', models.CharField(max_length=11)),
                ('jia_name', models.CharField(max_length=32)),
                ('yi_name', models.CharField(max_length=32)),
                ('start_data', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ht_money', models.CharField(max_length=11)),
                ('jia_leader', models.CharField(max_length=32)),
                ('yi_leader', models.CharField(max_length=32)),
                ('ht_content', models.TextField()),
                ('ht_remark', models.TextField()),
            ],
        ),
    ]
